/*! jcarousel.js bundle */
(function() {var _global = this||(1,eval)('this');$env = _global.$env||{};$env.builds = $env.builds||{};if (!$env.builds['jcarousel']) {$env.builds['jcarousel'] = 1689179351401;}if ($env.resource) $env.resource('jcarousel.js', {intact: false, loaded: (+new Date())});}).call((function() {return this;})());
if (window.$requires) $requires([	'jcarousel',	'jquery.easyzoom.js',	'external/jcarousellite_1.0.1.js'], {	isPreloaded: true});var isiPadeasyzoom=null!=navigator.userAgent.match(/iPad/i);
/*!
 * @name        easyzoom
 * @author       <>
 * @modified    Friday, May 15th, 2020
 * @version     2.5.2
 */
/*!
 * @name        easyzoom
 * @author       <>
 * @modified    Friday, May 15th, 2020
 * @version     2.5.2
 */
!function(t,e){'use strict';'function'==typeof define&&define.amd?define(['jquery'],function(t){e(t)}):'object'==typeof module&&module.exports?module.exports=t.EasyZoom=e(require('jquery')):t.EasyZoom=e(t.jQuery)}(this,function(t){'use strict';var e,i,o,s,h,a,n={loadingNotice:'Loading image',errorNotice:'The image could not be loaded',errorDuration:2500,linkAttribute:'href',preventClicks:!0,beforeShow:t.noop,beforeHide:t.noop,onShow:t.noop,onHide:t.noop,onMove:t.noop};function r(e,i){this.$target=t(e);this.opts=t.extend({},n,i,this.$target.data());void 0===this.isOpen&&this._init()}r.prototype._init=function(){this.$link=this.$target.find('a');this.$image=this.$target.find('img');this.$flyout=t('<div class="easyzoom-flyout" />');this.$notice=t('<div class="easyzoom-notice" />');this.$target.on({'mousemove.easyzoom touchmove.easyzoom':t.proxy(this._onMove,this),'mouseleave.easyzoom touchend.easyzoom':t.proxy(this._onLeave,this),'mouseenter.easyzoom touchstart.easyzoom':t.proxy(this._onEnter,this)})
;this.opts.preventClicks&&this.$target.on('click.easyzoom',function(t){t.preventDefault()})};r.prototype.show=function(t,h){var a=this;if(!1!==this.opts.beforeShow.call(this)){if(!this.isReady)return this._loadImage(this.$link.attr(this.opts.linkAttribute),function(){!a.isMouseOver&&h||a.show(t)});this.$target.append(this.$flyout);var n=this.$target.outerWidth(),r=this.$target.outerHeight(),c=this.$flyout.width(),l=this.$flyout.height(),d=this.$zoom.width(),p=this.$zoom.height();e=Math.ceil(d-c);i=Math.ceil(p-l);e<0&&(e=0);i<0&&(i=0);o=e/n;s=i/r;this.isOpen=!0;this.opts.onShow.call(this);t&&this._move(t)}};r.prototype._onEnter=function(t){var e=t.originalEvent.touches;this.isMouseOver=!0;if(!e||1==e.length){t.preventDefault();this.show(t,!0)}};r.prototype._onMove=function(t){if(this.isOpen){t.preventDefault();this._move(t)}};r.prototype._onLeave=function(){this.isMouseOver=!1;this.isOpen&&this.hide()};r.prototype._onLoad=function(t){if(t.currentTarget.width){this.isReady=!0;this.$notice.detach()
;this.$flyout.html(this.$zoom);this.$target.removeClass('is-loading').addClass('is-ready');t.data.call&&t.data()}};r.prototype._onError=function(){var t=this;this.$notice.text(this.opts.errorNotice);this.$target.removeClass('is-loading').addClass('is-error');this.detachNotice=setTimeout(function(){t.$notice.detach();t.detachNotice=null},this.opts.errorDuration)};r.prototype._loadImage=function(e,i){var o=new Image;this.$target.addClass('is-loading').append(this.$notice.text(this.opts.loadingNotice));this.$zoom=t(o).on('error',t.proxy(this._onError,this)).on('load',i,t.proxy(this._onLoad,this));o.style.position='absolute';o.src=e};r.prototype._move=function(t){if(0===t.type.indexOf('touch')){var n=t.touches||t.originalEvent.touches;h=n[0].pageX;a=n[0].pageY}else{h=t.pageX||h;a=t.pageY||a}var r=this.$target.offset(),c=h-r.left,l=a-r.top,d=Math.ceil(c*o),p=Math.ceil(l*s);if(d<0||p<0||d>e||p>i)this.hide();else{var u=-1*p,f=-1*d;this.$zoom.css({top:u,left:f});this.opts.onMove.call(this,u,f)}}
;r.prototype.hide=function(){if(this.isOpen&&!1!==this.opts.beforeHide.call(this)){this.$flyout.detach();this.isOpen=!1;this.opts.onHide.call(this)}};r.prototype.swap=function(e,i,o){this.hide();this.isReady=!1;this.detachNotice&&clearTimeout(this.detachNotice);this.$notice.parent().length&&this.$notice.detach();this.$target.removeClass('is-loading is-ready is-error');this.$image.attr({src:e,srcset:t.isArray(o)?o.join():o});this.$link.attr(this.opts.linkAttribute,i)};r.prototype.teardown=function(){this.hide();this.$target.off('.easyzoom').removeClass('is-loading is-ready is-error');this.detachNotice&&clearTimeout(this.detachNotice);delete this.$link;delete this.$zoom;delete this.$image;delete this.$notice;delete this.$flyout;delete this.isOpen;delete this.isReady};t.fn.easyZoom=function(e){return this.each(function(){var i=t.data(this,'easyZoom');i?void 0===i.isOpen&&i._init():t.data(this,'easyZoom',new r(this,e))})};return r});
!function(e){e.fn.jCarouselLite=function(t){t=e.extend({btnPrev:null,btnNext:null,btnGo:null,mouseWheel:!1,auto:null,speed:200,easing:null,vertical:!1,circular:!0,visible:3,start:0,scroll:1,beforeStart:null,afterEnd:null},t||{});return this.each(function(){var l=!1,n=t.vertical?'top':'left',i=t.vertical?'height':'width',s=e(this),r=e('ul',s),o=e('li',r),c=o.length,a=t.visible;if(t.circular){r.prepend(o.slice(c-1).clone()).append(o.slice(0,a).clone());t.start+=a}var u=e('li',r),f=u.length,d=void 0===t.active?t.start:t.active,b=Math.floor((f-1)/t.scroll)*t.scroll;s.css('visibility','visible');u.css({overflow:'hidden',float:t.vertical?'none':'left'});r.css({margin:'0',padding:'0',position:'relative','list-style-type':'none','z-index':'1'});s.css({overflow:'hidden',position:'relative','z-index':'2',left:'0px'});var v=t.vertical?u.outerHeight(!0):u.outerWidth(!0),h=v*f,p=v*a;s.css(i,p+'px');var x=Math.floor(d/t.scroll)*t.scroll;r.css(i,h+'px').css(n,-x*v);g(d);t.btnPrev&&e(t.btnPrev).on('click.jc',function(){
return g(d-t.scroll)});t.btnNext&&e(t.btnNext).on('click.jc',function(){return g(d+t.scroll)});t.btnGo&&e.each(t.btnGo,function(l,n){e(n).on('click.jc',function(){return g(t.circular?t.visible+l:l)})});t.mouseWheel&&s.mousewheel&&s.on('mousewheel',function(e,l){return g(l>0?d-t.scroll:d+t.scroll)});t.auto&&(self.setAuto=setInterval(function(){g(d+t.scroll)},t.auto+t.speed));function j(){return u.slice(d).slice(0,a)}function g(i){var s;if(!l){t.beforeStart&&t.beforeStart.call(this,j());if(t.circular)if(i<=t.start-a-1){r.css(n,-(f-2*a)*v+'px');d=i==t.start-a-1?f-2*a-1:f-2*a-t.scroll}else if(i>=f-a+1){r.css(n,-a*v+'px');d=i==f-a+1?a+1:a+t.scroll}else d=i;else{i>=f&&(i=f-1);i<0&&(i=0);d=i}l=!0;s=Math.floor(d/t.scroll)*t.scroll;r.animate('left'==n?{left:-((o.eq(s).position()||{}).left||0)}:{top:-s*v},t.speed,t.easing,function(){t.afterEnd&&t.afterEnd.call(this,j());l=!1});if(!t.circular){if(t.btnPrev){e(t.btnPrev).removeClass('disabled');0===s&&e(t.btnPrev).addClass('disabled')}if(t.btnNext){
e(t.btnNext).removeClass('disabled');s===b&&e(t.btnNext).addClass('disabled')}}}return!1}s.bind('go.jc',function(e,t){'undefined'==typeof t&&(t='+=1');var l='string'==typeof t&&/(\+=|-=)(\d+)/.exec(t);l&&(t='-='===l[1]?d-1*l[2]:d+1*l[2]);g(t)}).bind('endCarousel.jc',function(){if(self.setAuto){clearTimeout(self.setAuto);self.setAuto=void 0}t.btnPrev&&e(t.btnPrev).addClass(t.btnDisabledClass).unbind('.jc');t.btnNext&&e(t.btnNext).addClass(t.btnDisabledClass).unbind('.jc');t.btnGo&&e.each(t.btnGo,function(t,l){e(l).unbind('.jc')});s.unbind('.jc')})})}}(jQuery);
(function() {var resource = $env.resource('jcarousel.js');var now = (+new Date());resource.loaded = resource.loaded||now;resource.parsed = now;resource.intact = true;})();
// ----- End of jcarousel.js bundle -----
